### ISSUE TITLE
nextflow pull request failing

### ISSUE THREAD

**Issue by arwolf0808** [FischbachLab/nf-ninjaindex#1]
Hi - I get the below error and these links seem to not exist. Possibly on my end but other nf-core pull requests work. Maybe files got moved around? Thanks.

nextflow pull nf-core/ninjaindex
Checking nf-core/ninjaindex ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nf-core/ninjaindex/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/nf-core/ninjaindex/contents/main.nf

**Comment by xmeng** [comment]
I am sorry that the ninjaindex workflow has not been published to the nf-core yet. Please clone the repo or run this workflow directly from github via the aws batch. Please refer to the submission-examples file.
